### PR TITLE
Prepare for a first tagged release

### PR DESCRIPTION
**Pull request by jadb**

### CODE REVIEW

**Comment by ADmad** [comment]
Coveralls build needs to be updated to use PHP 7 or replace it with codecov.

What version do you plan to tag? Given the couple of open issues we haven't got to the bottom of, I wouldn't be comfortable making a stable release.

**Comment by jadb** [comment]
#17 should be resolved by #11 which I am wrapping up.

The other issue I will be looking into and trying to replicate with a test. Has anyone been able to replicate in a test? I'd gladly work on a fix for it - I haven't been running in issues as of late.

Was thinking to tag at least a `0.1`, keeping `1.0.x-dev` as alias until we official announce it stable.

**Comment by ADmad** [comment]
Sounds good.

**Comment by jadb** [comment]
@ADmad could you turn @codecov-io's notifications off? Am not sure how.

**Comment by ADmad** [comment]
Done

**Pull request merged**
