### PR TITLE
Sets Model.initialize in trait __construct method

### PR DESCRIPTION
**Pull request by andrej-griniuk**
A problem was occurring when models that have Footprint behaviour were initialised in component, before Footprint Model.initialize listener was getting set.

### CODE REVIEW

**Comment by ADmad** [comment]
Where exactly in component are you initializing models?

**Comment by andrej-griniuk** [comment]
In initialize()

**Comment by ADmad** [comment]
Does this fix your issue?  Because even if the listener does get attached earlier, the authentication routine would still not have run when your controller's `initilialize()` method is run, so user record won't be available to footprint.

**Comment by ADmad** [comment]
Your can avoid your problem by loading your models in `startup()` instead of `initialize()`.

**Comment by andrej-griniuk** [comment]
`startup` happens after controller's `beforeFilter`, where component's data is expected to be ready (and I think that's quite a common case), so that's too late. And component's `beforeFilter` is too early.

**Comment by ADmad** [comment]
Too late for what?  `AuthComponent::startup()` runs the authentication routine. So your table isn't going to get footprint info before `Controller.startup` event is triggered anyway even if required events are attached.

**Comment by andrej-griniuk** [comment]
If it's not an auth request `$this->Auth->user()` is available straightaway after loading the component

**Comment by ADmad** [comment]
You lost me. Please provide a test case showing that footprint info is available in beforeSave callback after this change.

**Comment by andrej-griniuk** [comment]
Added a test case.

**Comment by andrej-griniuk** [comment]
I understand that overwriting constructor in a trait looks dodgy, but leaving it as is would mean that Footprint behavior using models just can't be loaded before `startup()` fires, which I don't think is acceptable. Hope we can come up with a better solution.

**Comment by jadb** [comment]
Hey @andrej-griniuk,

I haven't been following this from early on but I *definitely* don't think a trait with a constructor is the way to go (according to my online education on the subject, its a NO NO).

I re-read and tried understanding the problem at hand. According to the test you added, you want the behavior to be usable after a call to `Auth::identify()`. Which by default is how it works for everyone. Now, if in your component where this is being used, you are able to call `Auth::identify()` before it like in the test OR anywhere in your code where this isn't working after calling the `Auth::identify()` method, you could just register to the `Auth.afterIdentify` event triggered by that method and attach the behavior to the model even dispatcher from there.

Let me know if that resolves it for you. 

@ADmad, any thoughts?

**Comment by ADmad** [comment]
> I haven't been following this from early on but I definitely don't think a trait with a constructor is the way to go (according to my online education on the subject, its a NO NO).

It's a big NO for me too. Even after this patch things will work as expected only if someone calls `Auth->identify()` manually before hand inside `initialize()`.

@andrej-griniuk's problem is easily avoided by loading his models in component's `startup()` instead of `initialize()`.

So I am :-1: for this patch.  We can just update the README to clarify the model's loaded in `initialize()` of controller or component won't get footprint attached and they should instead use `Controller::beforeFilter()` or `Component::start()`, that won't be limiting in any way.

**Pull request closed without merging**
